### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by theyash14** [Kazuhito00/NARUTO-HandSignDetection#4]
<img width="212" alt="Screenshot 2023-03-22 112454" src="https://user-images.githubusercontent.com/53083827/226814814-43ae4e9a-f180-4fb4-be62-9b182c463b97.png">

d:/Documents/Projects/Uzumaki/NARUTO-HandSignDetection/simple_demo.py
Traceback (most recent call last):
  File "d:\Documents\Projects\Uzumaki\NARUTO-HandSignDetection\simple_demo.py", line 162, in <module>
    main()

  File "d:\Documents\Projects\Uzumaki\NARUTO-HandSignDetection\simple_demo.py", line 92, in main
    yolox = YoloxONNX(

  File "d:\Documents\Projects\Uzumaki\NARUTO-HandSignDetection\model\yolox\yolox_onnx.py", line 32, in __init__
    self.onnx_session = onnxruntime.InferenceSession(

  File "C:\Users\Yash\Envs\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)

  File "C:\Users\Yash\Envs\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 397, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)

onnxruntime.capi.onnxruntime_pybind11_state.**NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from model/yolox/yolox_nano.onnx failed:Load model model/yolox/yolox_nano.onnx failed. File doesn't exist**

**Comment by theyash14** [comment]
It's working now, change current working directory.
